-- 20260215_autonomous_followup_sequences_supabase.sql
-- Autonomous Follow-up System (Supabase/Postgres)
-- Keeps sequence/step/enrollment/message IDs as BIGINT for compatibility with existing API routes.

-- Sequence definitions
CREATE TABLE IF NOT EXISTS followup_sequences (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id TEXT NOT NULL,

  sequence_name TEXT NOT NULL,
  sequence_type TEXT NOT NULL DEFAULT 'nurture',
  description TEXT,

  target_customer_type TEXT,
  target_deal_stage TEXT,

  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  max_enrollments INTEGER,
  current_enrollments INTEGER NOT NULL DEFAULT 0,

  total_sent INTEGER NOT NULL DEFAULT 0,
  total_opened INTEGER NOT NULL DEFAULT 0,
  total_clicked INTEGER NOT NULL DEFAULT 0,
  total_replied INTEGER NOT NULL DEFAULT 0,
  total_converted INTEGER NOT NULL DEFAULT 0,

  open_rate DOUBLE PRECISION NOT NULL DEFAULT 0.0,
  click_rate DOUBLE PRECISION NOT NULL DEFAULT 0.0,
  reply_rate DOUBLE PRECISION NOT NULL DEFAULT 0.0,
  conversion_rate DOUBLE PRECISION NOT NULL DEFAULT 0.0,

  created_by TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_followup_sequences_tenant ON followup_sequences(tenant_id);
CREATE INDEX IF NOT EXISTS idx_followup_sequences_active ON followup_sequences(is_active);
CREATE INDEX IF NOT EXISTS idx_followup_sequences_type ON followup_sequences(sequence_type);

-- Sequence steps
CREATE TABLE IF NOT EXISTS sequence_steps (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sequence_id BIGINT NOT NULL REFERENCES followup_sequences(id) ON DELETE CASCADE,
  tenant_id TEXT NOT NULL,

  step_number INTEGER NOT NULL,
  step_name TEXT NOT NULL,

  delay_days INTEGER NOT NULL DEFAULT 0,
  delay_hours INTEGER NOT NULL DEFAULT 0,
  send_time TEXT,
  skip_weekends BOOLEAN NOT NULL DEFAULT TRUE,

  channel TEXT NOT NULL,
  subject_line TEXT,
  message_body TEXT NOT NULL,

  uses_placeholders BOOLEAN NOT NULL DEFAULT TRUE,

  is_variant BOOLEAN NOT NULL DEFAULT FALSE,
  variant_group TEXT,
  variant_split_percentage INTEGER NOT NULL DEFAULT 50,

  cta_text TEXT,
  cta_url TEXT,

  sent_count INTEGER NOT NULL DEFAULT 0,
  opened_count INTEGER NOT NULL DEFAULT 0,
  clicked_count INTEGER NOT NULL DEFAULT 0,
  replied_count INTEGER NOT NULL DEFAULT 0,

  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  UNIQUE(sequence_id, step_number)
);

CREATE INDEX IF NOT EXISTS idx_sequence_steps_sequence ON sequence_steps(sequence_id);
CREATE INDEX IF NOT EXISTS idx_sequence_steps_number ON sequence_steps(step_number);

-- Sequence enrollments
CREATE TABLE IF NOT EXISTS sequence_enrollments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sequence_id BIGINT NOT NULL REFERENCES followup_sequences(id) ON DELETE CASCADE,
  tenant_id TEXT NOT NULL,

  customer_id TEXT,
  contact_id TEXT,
  deal_id TEXT,

  enrolled_by TEXT,
  enrollment_source TEXT NOT NULL DEFAULT 'manual',

  enrollment_status TEXT NOT NULL DEFAULT 'active',
  current_step INTEGER NOT NULL DEFAULT 0,

  enrolled_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  next_send_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  cancelled_at TIMESTAMPTZ,
  cancellation_reason TEXT,

  total_messages_sent INTEGER NOT NULL DEFAULT 0,
  total_opened INTEGER NOT NULL DEFAULT 0,
  total_clicked INTEGER NOT NULL DEFAULT 0,
  total_replied INTEGER NOT NULL DEFAULT 0,

  converted BOOLEAN NOT NULL DEFAULT FALSE,
  converted_at TIMESTAMPTZ,
  conversion_value DOUBLE PRECISION
);

CREATE INDEX IF NOT EXISTS idx_enrollments_sequence ON sequence_enrollments(sequence_id);
CREATE INDEX IF NOT EXISTS idx_enrollments_tenant_status ON sequence_enrollments(tenant_id, enrollment_status);
CREATE INDEX IF NOT EXISTS idx_enrollments_customer ON sequence_enrollments(customer_id);
CREATE INDEX IF NOT EXISTS idx_enrollments_next_send ON sequence_enrollments(next_send_at);

-- Message delivery log
CREATE TABLE IF NOT EXISTS sequence_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  enrollment_id BIGINT NOT NULL REFERENCES sequence_enrollments(id) ON DELETE CASCADE,
  step_id BIGINT NOT NULL REFERENCES sequence_steps(id) ON DELETE CASCADE,
  tenant_id TEXT NOT NULL,

  channel TEXT NOT NULL,
  recipient_contact TEXT NOT NULL,
  subject_line TEXT,
  message_body TEXT NOT NULL,

  scheduled_send_at TIMESTAMPTZ NOT NULL,
  actual_sent_at TIMESTAMPTZ,

  delivery_status TEXT NOT NULL DEFAULT 'pending',
  failure_reason TEXT,

  opened_at TIMESTAMPTZ,
  first_clicked_at TIMESTAMPTZ,
  replied_at TIMESTAMPTZ,
  reply_text TEXT,

  open_count INTEGER NOT NULL DEFAULT 0,
  click_count INTEGER NOT NULL DEFAULT 0,

  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_sequence_messages_enrollment ON sequence_messages(enrollment_id);
CREATE INDEX IF NOT EXISTS idx_sequence_messages_status ON sequence_messages(delivery_status);
CREATE INDEX IF NOT EXISTS idx_sequence_messages_scheduled ON sequence_messages(scheduled_send_at);

-- Trigger conditions for auto-enrollment
CREATE TABLE IF NOT EXISTS sequence_triggers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sequence_id BIGINT NOT NULL REFERENCES followup_sequences(id) ON DELETE CASCADE,
  tenant_id TEXT NOT NULL,

  trigger_name TEXT NOT NULL,
  trigger_type TEXT NOT NULL,
  trigger_conditions JSONB NOT NULL DEFAULT '{}'::jsonb,

  apply_to_customer_type TEXT,
  apply_to_region TEXT,

  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  priority INTEGER NOT NULL DEFAULT 1,

  times_triggered INTEGER NOT NULL DEFAULT 0,
  successful_enrollments INTEGER NOT NULL DEFAULT 0,

  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_sequence_triggers_sequence ON sequence_triggers(sequence_id);
CREATE INDEX IF NOT EXISTS idx_sequence_triggers_type ON sequence_triggers(trigger_type);
CREATE INDEX IF NOT EXISTS idx_sequence_triggers_active ON sequence_triggers(is_active);

-- Unsubscribe management
CREATE TABLE IF NOT EXISTS sequence_unsubscribes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id TEXT NOT NULL,

  customer_id TEXT,
  email TEXT,
  phone TEXT,

  unsubscribe_type TEXT NOT NULL DEFAULT 'all_sequences',
  sequence_id BIGINT,
  sequence_type TEXT,

  unsubscribe_reason TEXT,
  feedback TEXT,

  unsubscribed_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_unsubscribes_customer ON sequence_unsubscribes(customer_id);
CREATE INDEX IF NOT EXISTS idx_unsubscribes_email ON sequence_unsubscribes(email);
CREATE INDEX IF NOT EXISTS idx_unsubscribes_phone ON sequence_unsubscribes(phone);
