/**
 * @title AI Product Description Service
 * @description Manages the logic for automatically generating product descriptions using AI.
 */
const { supabase, openai } = require('./config');

/**
 * Generates a compelling, sales-focused description for a product based on its name.
 * @param {string} productName The name of the product.
 * @returns {Promise<string>} The AI-generated description.
 */
const generateDescriptionForProduct = async (productName) => {
    try {
        const response = await openai.chat.completions.create({
            model: "gpt-4-turbo",
            messages: [{
                role: "system",
                content: "You are an expert e-commerce copywriter. Based on the product name provided, write a compelling, friendly, and concise sales description of about 20-30 words. Focus on the key benefit for the customer. Do not use placeholders like '[Product Name]'."
            }, {
                role: "user",
                content: productName
            }],
            temperature: 0.7,
        });
        return response.choices[0].message.content.trim();
    } catch (error) {
        console.error(`Error generating description for ${productName}:`, error.message);
        return null; // Return null on error so we can skip it
    }
};

/**
 * Finds all products without a description and generates one for them using AI.
 * This function is designed to be run periodically by a scheduler.
 */
const generateMissingDescriptions = async () => {
    try {
        // 1. Find all products where the description is null or empty and was not previously generated by AI.
        const { data: products, error } = await supabase
            .from('products')
            .select('id, name')
            .or('description.is.null,description.eq.')
            .eq('description_generated_by_ai', false);

        if (error) throw error;
        if (!products || products.length === 0) {
            console.log('No products found needing an AI-generated description.');
            return;
        }

        console.log(`Found ${products.length} product(s) needing an AI-generated description. Generating now...`);

        // 2. Loop through each product and generate a description.
        for (const product of products) {
            const newDescription = await generateDescriptionForProduct(product.name);

            if (newDescription) {
                // 3. Update the product record with the new description and set the flag.
                await supabase
                    .from('products')
                    .update({
                        description: newDescription,
                        description_generated_by_ai: true
                    })
                    .eq('id', product.id);
                
                console.log(`- Generated description for: ${product.name}`);
            }
        }
        
        console.log('Finished generating missing product descriptions.');

    } catch (error) {
        console.error('Error in generateMissingDescriptions:', error.message);
    }
};

module.exports = {
    generateMissingDescriptions,
};
